import type { NextPage } from "next";
import dynamic from 'next/dynamic'
import Head from "next/head";
import { Suspense } from 'react'
import { useSession, signIn, signOut } from "next-auth/react";


const Home: NextPage = () => {
  const { data: session } = useSession();

  const DynamicProducts = dynamic(() => import('../components/products'), {
    suspense: true,
  })

  if (session) {
    return (
      <div>
        Welcome user
        <br />
        <button onClick={() => signOut()}>Sign out</button>
      </div>
    );
  }
  return (
    <div>
      <Head>
        <title>Eco-Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Suspense fallback={`Loading...`}>
          <DynamicProducts />
        </Suspense>
      </div>
    </div>
  );
};


export default Home;
